import type { Persona } from '@homc/shared'

export const personas: Persona[] = [
  {
    id: 'power-user',
    name: 'Alex (Power User)',
    description: 'Tech-savvy, fast-moving, low tolerance for friction. Clicks fast, skips reading, abandons quickly if confused.',
    patience: 0.2,
    trustThreshold: 0.7,
    explorationDepth: 0.4,
    errorTolerance: 0.2,
    speedBias: 0.9,
  },
  {
    id: 'cautious-user',
    name: 'Morgan (Cautious User)',
    description: 'Privacy-conscious, reads everything carefully, hesitates before sharing personal data.',
    patience: 0.8,
    trustThreshold: 0.3,
    explorationDepth: 0.7,
    errorTolerance: 0.6,
    speedBias: 0.2,
  },
  {
    id: 'confused-user',
    name: 'Jamie (First-Timer)',
    description: 'New to online shopping, easily confused by jargon, needs clear labels and obvious buttons.',
    patience: 0.6,
    trustThreshold: 0.5,
    explorationDepth: 0.5,
    errorTolerance: 0.5,
    speedBias: 0.4,
  },
  {
    id: 'impulse-buyer',
    name: 'Jordan (Impulse Buyer)',
    description: 'Shopping on a whim, wants to act fast to grab a deal. Zero tolerance for popups, long forms, or anything that slows them down. Abandons at the first sign of friction.',
    patience: 0.1,
    trustThreshold: 0.9,
    explorationDepth: 0.2,
    errorTolerance: 0.1,
    speedBias: 1.0,
  },
  {
    id: 'accessibility-user',
    name: 'Dana (Accessibility-Focused)',
    description: 'Relies on keyboard navigation and clear labels. Reads field hints carefully and notices poor tab order and missing labels. Patient but frustrated by visually cluttered layouts.',
    patience: 0.9,
    trustThreshold: 0.5,
    explorationDepth: 0.8,
    errorTolerance: 0.7,
    speedBias: 0.1,
  },
  {
    id: 'thorough-user',
    name: 'Sam (Thorough Evaluator)',
    description: 'Reads every field label, checks all options before committing. Prefers explicit confirmation.',
    patience: 0.9,
    trustThreshold: 0.6,
    explorationDepth: 0.9,
    errorTolerance: 0.8,
    speedBias: 0.1,
  },
  {
    id: 'mobile-user',
    name: 'Riley (Mobile-First)',
    description: 'Uses phone with fat-finger taps, prefers large touch targets, frustrated by small text and tiny buttons.',
    patience: 0.5,
    trustThreshold: 0.5,
    explorationDepth: 0.3,
    errorTolerance: 0.4,
    speedBias: 0.6,
  },
]
